---
defaults:
  - iwildcam
  - _self_

training_mode: step
groupby_fields: [location]
train_batch_size_l: 16
train_batch_size_u: 16
use_unlabeled: true

train_transforms_l: 
  _target_: torchvision.transforms.Compose
  transforms: 
    - _target_: torchvision.transforms.Resize
      size: ${ dm.target_resolution }
    - _target_: torchvision.transforms.CenterCrop
      size: ${ dm.target_resolution }
    - _target_: torchvision.transforms.RandomHorizontalFlip
    - _target_: torchvision.transforms.RandAugment
      num_ops: 2
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]

test_transforms: 
  _target_: torchvision.transforms.Compose
  transforms: 
    - _target_: torchvision.transforms.Resize
      size: ${ dm.target_resolution }
    - _target_: torchvision.transforms.CenterCrop
      size: ${ dm.target_resolution }
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
